apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  labels:
    name: fleetman-gateway-svc
  namespace: fleetman
spec:
  selector:
    app: fleetman-gateway
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: fleetman-gateway-ports
    protocol: TCP
    port: 8080
    targetPort: 8080
    