apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fleetman-tracker-dpm
  namespace: fleetman
  labels:
    app:  tracker
spec:
  selector:
    matchLabels:
      app: fleetman-tracker
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: fleetman-tracker
      labels:
        app:  fleetman-tracker
        tier: backend
        version: v1
    spec:
      containers:
      - name:  fleetman-tracker
        image:  richardchesterwood/k8s-fleetman-position-tracker:release1
        ports:
          - containerPort: 8080
        env:
           - name: SPRING_PROFILES_ACTIVE
             value: local-microservice
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 500Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
      restartPolicy: Always