apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  labels:
    name: fleetman-webapps-svc
  namespace: fleetman
spec:
  selector:
    app: fleetman-webapp
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: fleetman-webapps-ports
    protocol: TCP
    port: 80
    targetPort: 80
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.